import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
	server: {
		GITHUB_CLIENT_ID: z.string().min(1),
		GITHUB_CLIENT_SECRET: z.string().min(1),
		BETTER_AUTH_SECRET: z.string().min(32),
		BETTER_AUTH_URL: z.string().url(),
		ANTHROPIC_API_KEY: z.string().min(1),
		OPENAPI_KEY: z.string().min(1),
		E2B_API_KEY: z.string().min(1),
		INNGEST_EVENT_KEY: z.string().min(1),
		INNGEST_SIGNING_KEY: z.string().min(1),
		MIXEDBREAD_API_KEY: z.string().min(1),
		OPEN_ROUTER_API_KEY: z.string().min(1),
		SLACK_CLIENT_ID: z.string().min(1),
		SLACK_CLIENT_SECRET: z.string().min(1),
		VERCEL_OIDC_TOKEN: z.string().optional(),
		SUPER_MEMORY_API_KEY: z.string().min(1),
		DATABASE_URL: z.string().url(),
		UPSTASH_REDIS_REST_URL: z.string().url(),
		UPSTASH_REDIS_REST_TOKEN: z.string().min(1),
	},
	client: {
		NEXT_PUBLIC_APP_URL: z.string().url(),
	},
	runtimeEnv: {
		GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
		GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
		BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
		BETTER_AUTH_URL: process.env.BETTER_AUTH_URL,
		ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
		OPENAPI_KEY: process.env.OPENAPI_KEY,
		E2B_API_KEY: process.env.E2B_API_KEY,
		INNGEST_EVENT_KEY: process.env.INNGEST_EVENT_KEY,
		INNGEST_SIGNING_KEY: process.env.INNGEST_SIGNING_KEY,
		MIXEDBREAD_API_KEY: process.env.MIXEDBREAD_API_KEY,
		OPEN_ROUTER_API_KEY: process.env.OPEN_ROUTER_API_KEY,
		SLACK_CLIENT_ID: process.env.SLACK_CLIENT_ID,
		SLACK_CLIENT_SECRET: process.env.SLACK_CLIENT_SECRET,
		VERCEL_OIDC_TOKEN: process.env.VERCEL_OIDC_TOKEN,
		SUPER_MEMORY_API_KEY: process.env.SUPER_MEMORY_API_KEY,
		DATABASE_URL: process.env.DATABASE_URL,
		NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
		UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
		UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
	},
	skipValidation: !!process.env.SKIP_ENV_VALIDATION,
	emptyStringAsUndefined: true,
});
